LUT: 
    lut_params: 'lut_params/prosail_danner-etal_switzerland_nosoil_deris_zofe.csv' 
    # Note: prosail_danner-etal_europe_nosoil_snap.csv --> overestimated LAI
    # According to Meeting with Helge Aasen on 18.09.2026
    # Make a mix of Danner Publication and Lukas Graf
    # https://www-sciencedirect-com.agros.swissconsortium.ch/science/article/pii/S003442572300411X
    # https://www.sciencedirect.com/science/article/pii/S092427162100023X
    lut_size : 5000 # Train 50k, Test 10k, Val 5k
    sampling_method: 'FRS'
    apply_glai_ccc_constraint: false
    apply_chlorophyll_carotiniod_constraint: false
    codistribution: null #'lut_params/codistribution.csv'
    

RTM:
    sensor : 'Hyspex' # among ['Sentinel2A', 'Sentinel2B', 'PlanetSuperDove', 'Hyspex']
    fpath_srf : 'data/mjolnir_wvl_fwhm.csv' #'data/S2-SRF_COPE-GSEG-EOPG-TN-15-0007_3.1.xlsx'   for Sentinel-2
    remove_invalid_green_peaks : true
    linearize_lai : false
    
out_dir : 'results'
soil_path : null # or null
traits : ['lai', 'cab', 'ccc', 'car']



